### ISSUE TITLE
Don't show clear text e-mails

### ISSUE THREAD

**Issue by hamoid** [rubyberlin/code-of-conduct#69]
Currently all our e-mails are displayed in clear, which is great for receiving spam...

**Comment by chastell** [comment]
I assumed one of the points of providing email addresses and phone numbers is for the participants to easily contact the organisers when there’s a need. For Warsaw Ruby Users Group I registered an additional phone number (redirected to my mobile) and added my email address which I publish everywhere anyway, but a dedicated alias (or a `+` email address extension, like `foo+bar@example.com`) would work as well.

I think spam filtering is a solved problem. `<anecdata>`I receive emails on 17 addresses (some going back to mid-1990s, most published verbatim online) and while I do get a few thousand spam emails a week I haven’t seen a false positive in months and see one-two false negatives a week.`</anecdata>` I strongly disagree with the ‘let’s not publish (or cleverly encode) email addresses in cleartext because spambots can find them’ notion – this creates accessibility issues and offloads dealing with one’s spam to others.

**Comment by PragTob** [comment]
Hi there @hamoid 

pretty much what @chastell said - email addresses and telephone numbers are provided for the purpose of contacting organizers, especially in case an incident happens.

To cite this code of conduct:

> If you are subject to or witness unacceptable behavior, or have any other concerns, please notify a community organizer as soon as possible. You can find a list of organizers to contact for each of the supporters of this code of conduct at the bottom of this page.

Hence emails won't be obfuscated or removed. If I misunderstood what you wanted us to do, please let me know and we can discuss doing that.

If you have a problem with that, please send a PR removing your email address or changing the email address. I strongly advise you to have at least one email and one phone number there per group. It is important that attendees can direct there concerns or emergency calls somewhere.

Cheers,
Tobi

**Comment by transfluxus** [comment]
Cool, I'm gonna send a PR to replace my mail address as well.

I don't think any of our attendies would ever linger around on a rubyberlin github page in order to find our contact details. and it's on you to decide for others what they find private enough or not. you ask them if they are okay with it!

**Comment by skade** [comment]
@transfluxus @hamoid I added a clarification about the optionality of contact data and the reason behind publication on this site to the README.

https://github.com/rubyberlin/code-of-conduct#why-is-my-contact-data-public

It was not our intention to force any kind of decision here.

**Comment by hamoid** [comment]
I only mentioned the spam side, but what I dislike more is that the data stays there forever, makes my contact data easily indexable, and it links my person to other people in that who list I don't know. It makes [social engineering](https://en.wikipedia.org/wiki/Social_engineering_%28security%29) easier.

I would have liked to be asked if it was ok to put my contact data in GitHub.
Removing the data for real (from history too) seems complicated: https://help.github.com/articles/remove-sensitive-data/

**Comment by Xylakant** [comment]
All supporter data here was added via a pull request, yours was added in 
https://github.com/rubyberlin/code-of-conduct/commit/e3119a6e1876ccaff47d36475a56a95b725a8fa7

I understand your problem, but the person to direct your complaint to would be Raphaël who added it and created the PR. Effectively he published it.
