### ISSUE TITLE
In-Person meeting for future changes

### ISSUE THREAD

**Issue by skade** [rubyberlin/code-of-conduct#86]
Hi,

it seems that this issue tracker is not the place to get stuff done and some needs to be done.

Therefore, I propose we spend an evening on this thing to decided on some of the open, lingering issues and also make sure the current maintainers are properly introduced.

I propose the end of march for such a date. I would enjoy if some translators could join in (possibly via Skype/Hangouts)

Please mention open topics that can be covered in an evening in this thread. My list is:
- [ ] https://github.com/rubyberlin/code-of-conduct/issues/81 ; https://github.com/rubyberlin/code-of-conduct/issues/58
- [ ] https://github.com/rubyberlin/code-of-conduct/issues/44
- [ ] https://github.com/rubyberlin/code-of-conduct/issues/7
- [ ] https://github.com/rubyberlin/code-of-conduct/pull/76

Best,
Florian

**Comment by eljojo** [comment]
I would love to join over skype. I think this meeting makes sense.

**Comment by 1000miles** [comment]
@skade Thank you, I am in.

I would suggest to short summarize in advance each open issue and pull request to be more prepared and therefore effective at the meeting, otherwise I assume we need a second meeting for this. ;) As far as I can see a lot of tickets are currently dependent on clear decisions (e.g. amendments, licences, versioning, collaboration, etc.) which makes it hard for people to progress with their tickets. 

I am not sure if that makes sense to gather also the translators in the first meeting, for example we need to enable a system where we can speed up and extend the translations part but before we can do this, we need to clarify at least some english/german content tickets. And before we can do that, we might need input from collaborators. There seems to be currently a long tail of dependencies.

Short summary: we need a plan where we can list down the tasks into smaller and clearer steps. 
```
Example:

Topic A: Licencing
Milestone 1
Issue => Solution
Issue => Solution
Evaluation

Topic B: Community, Culture, Commitment
Milestone 2
Issue => Solution
Issue => Solution
Evaluation

Topic C: Content Implementation
Milestone 3
Issue => Solution
Issue => Solution
Evaluation

Topic D: Translations
Milestone 4
Issue => Solution
Issue => Solution
Evaluation

Topic D: Other Improvements (e.g. Wiki, Workshops, etc.)
Milestone 5
Issue => Solution
Issue => Solution
Evaluation

```
After reading the long discussions: Maybe it helps to think about to whom a Code of Conduct is primarily dedicated to, those who are less privileged and vulnerable to discriminations or those who don't want to be "restricted in their freedom to express themselves" while belonging to the more privileged part of the community? In my opinion we can close some tickets (most of them are content-related) easier after we have clarified this question. 

Nevertheless I would like to emphasize that a Code of Conduct is technically just a written sheet, what more important is is a community behind it that is willing to listen and back those who need protection the most. We can only become more inclusive if we go further than a Code of Conduct by looking at the barriers surrounding us (which we partly don't see if we belong to the more privileged part).

**Comment by lauralindal** [comment]
Hi, I'm in, too!

I would suggest that we go through the open tickets together and then decide what to do. Meaning: If we can change something right away, we should. If it takes longer, we can plan the steps in the way @1000miles suggests.

As @skade suggested, march would be great. Let's figure out a date: http://doodle.com/poll/p32mmcr3xafw6dzf (Also, I'm not exactly sure if/how we separate between translators and collaborators. I would generally say that anyone who would like to contribute more than "simply" translations is welcome to contribute?)

**Comment by skade** [comment]
Notice: This meeting is happening at the RailsGirls retreat.
